### ISSUE TITLE
Tech Debt client dashboard: 'Annual spend' is a floor with no flag, while 'savings' next to it has one

### ISSUE THREAD

**Issue by gene-png** [gene-png/080426SHIELD#126]
Found by an adversarial review of the item-9 twin-sweep. **MVP item 9.** D-052's shape, expressed a way the original grep could not match.

## The asymmetry

`routes/clients.py:877-879`:

```python
cost = float(it.annual_cost_usd) if it.annual_cost_usd is not None else 0.0
annual_spend += cost
```

An uncosted item contributes **0** and is counted in `total_applications = len(items)`.

`savings` gets a floor flag for exactly this reason — `schemas/clients.py`:

```python
annual_spend_usd: float                                    # <- no flag
savings_cost_known: bool  # False when a CUT item lacked a cost (savings is a floor)
```

Same exclusion, same direction, one disclosed and one not. `tech_debt/overlap.py` even tracks `no_cost_count` — for the **admin** view. The client payload has no such field.

## What the client reads

> **Total applications 412 · Annual spend $3.1M**

with 60 of those applications contributing nothing to the figure, rendered as `—` in the per-row table beneath, and nothing saying the headline is a floor.

This is the same understatement direction as the 2026-08-04 calibration incident that D-052 records — a partial total presented as a total.

## Suggested direction

Add the equivalent flag (`spend_cost_known`, or a count of uncosted items) and surface it beside the figure, the way `savings_cost_known` already is. The count exists; it just is not passed to the client.

**Comment by gene-png** [comment]
An adversarial sweep run for the item-9 work independently rediscovered this issue and added a **second dimension** the description does not cover. Recording it here rather than filing separately, since it is the same figure on the same surface.

The issue as filed is about **uncosted items**: `annual_cost_usd is None` contributes `0.0` and is still counted in `total_applications`.

The sweep found that **excluded rows are missing entirely**, which is a larger gap and has an explicit totality claim attached to it:

- `routes/clients.py:872-894` re-derives portfolio spend inline over `CapabilityItem` rows only. It never calls `build_context`, `reconciliation_line` or `cost_label`. The `cap_list` (`cl`, line 851) that carries `source_rows_total` and `excluded_rows` is already in hand at that point and is never read.
- `schemas/clients.py:291-314` — `TechDebtDashboardResponse` has no `source_rows_total` / `excluded_count` / `included_count` field, so there is nowhere to put the disclosure even if it were computed.
- `apps/web/src/components/dashboards/techDebt/TechDebtDashboard.tsx:164-168` renders it as `label="Annual license spend"`, `sub="Across all tools"` — an explicit claim of totality over a partial figure.

**The rule it violates is already written in its own twin.** `app/tech_debt/exporters.py:73-75`:

```python
def cost_label(...):
    """Never call a partial figure a total (UX finding #4)."""
```

and the PDF/DOCX/XLSX carry *"Figures below cover the included rows only, not the whole upload."* So the exporter discloses and the dashboard does not, on the same underlying list — the same admin-vs-client asymmetry pattern as #114.

Worked scenario on the recorded 28-row upload with 2 rows excluded: the released PDF says `28 rows received · 26 included · 2 excluded` and `Included annual cost: $3,368,000`, while the client dashboard for that same list says `Annual license spend $3,368,000 — Across all tools`. Same $240,000 unstated, on the surface the client actually opens.

Also worth noting for whoever picks this up: `total_applications` (line 933) has the same shape and additionally counts bundle components, which `build_context:112` deliberately excludes via `parent_item_id is None`. So the count and the spend are inconsistent with the exporter in two different directions.

Why the original sweep missed it: `routes/clients.py` is a reimplementation, so no call-site sweep of `build_context` reaches it. Same shape as #84 and #132 — grep the symptom, not the symbol.
